import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { list } from 'postcss'
export default function Home() {
  return (
    <>
      <Head>
        <title>Get Your Dream Job | Real Fast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/realfast_logo.png" />
      </Head>
      <main>
        <nav className={style.navbar}>
          <ul className={styles.navSection}>
            <li className={styles.brandSection}>
              <span className={styles.brandName}>Real Fast</span>
              <image width={38} height {38} src='/realfast_logo.png'/>
            </li>
            <li>
              <link href='#'>Find Jobs</link>
            </li>
          </ul>
          <ul className={styles.navSection}>
            <li>
            <link href='#' className={styles.navText}>Sign in</link>
            </li>
            <li>
            <link href='#' className={styles.navText}>Post a Job</link>
            </li>
          </ul>
        </nav>
      </main>
    </>
  )
}

const styles = {
  navBar:'h-[60px] flex flex-row justify-between items-center px-3 border border-gray-200 shadow-md'
  navSection: 'flex flex-row space-x-3',
  brandSection:'flex flex-row gap-2',
  brandName:'font-reading text-2xl text-purple-600 font-bold',
  navText: 'text-gray-700 hover:text-purple-600',
  seperator:'border border-r-2'
}
